# Site settings
name: Sergio Forés
title: Sergio Forés
version: v.0.6
email: sergiofores@gmail.com
description: Desarrollador y diseñador de proyectos
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sergiofores.es" # the base hostname & protocol for your site
twitter_username: t0tinspire
github_username: t0t
codepen_username: t0t
facebook_username: sergioforesstudio
linkedin_username: sergiofores

# Minification
sass:
  sass_dir: _sass
  style: compressed

collections:
  works:
    output: true

permalink: /:title/

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - CNAME
