# Site settings
name: Sergio Forés
title: Sergio Forés
version: v.0.6
email: sergiofores@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desarrollador y diseñador de proyectos
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sergiofores.es" # the base hostname & protocol for your site
twitter_username: t0tinspire
github_username: t0t
codepen_username: t0t
facebook_username: sergioforesstudio
linkedin_username: sergiofores

# Minification
sass:
  style: compressed

collections:
  works:
    output: true

# Build settings
markdown: kramdown

exclude:
  - package.json
  - node_modules
  - gulpfile.js
